version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Enter_Your_Password_Here_1234
      - ACCEPT_EULA=Y
  webapi:
    build:
      context: .
      dockerfile: src/NetApiCleanTemplate.WebApi/Dockerfile
    depends_on:
      - "sqlserver"
