<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a1f559ec-399f-4213-91de-75d4ebff9139</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  
  <PropertyGroup>
    <GenerateRuntimeConfigurationFiles>True</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.14.0" />
	<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
	<PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
	<PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
	<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
	<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetApiCleanTemplate.Core\NetApiCleanTemplate.Core.csproj" />
    <ProjectReference Include="..\NetApiCleanTemplate.Infrastructure\NetApiCleanTemplate.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logs\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>

